### ISSUE TITLE
CNAME config

### ISSUE THREAD

**Issue by bbucsy** [kir-dev/airsoft#135]
Get in contact with **KSZK** and request a production domain, preferably `http://airsoft.sch.bme.hu/`

**Comment by triszt4n** [comment]
https://support.sch.bme.hu/open.php és itt Hálózat / DNS kéréssel lehet kérni. Érdemes minél előbb, ha már tudod, mit szeretnél kérni tőlük, kb 1,5 hét lesz az átfutási idő
